### ISSUE TITLE
Blog has Item 1 Item 2 Item 3 after more than 2 entries are added

### ISSUE THREAD

**Issue by nathalie-ckc** [OpenAMP/website#55]
I filed ITS-12679 with Linaro IT.

@pcolmer advises that the best way forward would be to get the OpenAMP website upgraded to a newer version of the Jumbo Jekyll Theme as that doesn't appear to have this code or requirement in it.

@kylekirkby is currently out of office, so filing this GitHub Issue as a reminder for the upgrade.

**Comment by nathalie-ckc** [comment]
@kylekirkby ,
After the version upgrade, please remove the workaround file _includes/blog-filler-element.html.

Thanks!
-Nathalie

**Comment by pcolmer** [comment]
Also being tracked at https://projects.linaro.org/browse/WEBDEV-1039.
