### ISSUE TITLE
Logo update

### ISSUE THREAD

**Issue by maartenwrs** [OpenAMP/website#65]
Wind River has a new branding and we need to request that our logo at https://www.openampproject.org/about be updated.  I have attached it.  Thank you,
Maarten
![RGB - WNDRVR-Logo-Black-Teal](https://user-images.githubusercontent.com/6001501/119545871-47434380-bd61-11eb-9932-ffeb6859f32b.png)

**Comment by nathalie-ckc** [comment]
Addressed by PR #68
