### ISSUE TITLE
Update logos in docs/presentations/OpenAMP-Elevator-Pitch-2022-Q1.pdf

### ISSUE THREAD

**Issue by nathalie-ckc** [OpenAMP/website#91]
- [x] ST new logo received from Arnaud in 2022
- [x] Move Siemens to correct alphabetical position
- [x] Update Xilinx to AMD Xilinx logo
- [x] Update https://www.openampproject.org/ to point to the new PDF

**Comment by pcolmer** [comment]
@nathalie-ckc is there an action on Linaro web development team here?

**Comment by nathalie-ckc** [comment]
@philip-linaro thanks for checking. No action for you, just has not bubbled up my backlog yet.

**Comment by nathalie-ckc** [comment]
PR #120 also updates Linaro logo and reflects latest membership list.
